version: '3'
services:
  kkemu:
    image: kktech/kkemu:latest
    build:
      context: '../../'
      dockerfile: 'scripts/emulator/Dockerfile'
    networks:
      - local-net
    ports:
      - "127.0.0.1:21324:21324/udp"
      - "127.0.0.1:21325:21325/udp"
      - "127.0.0.1:5000:5000"
networks:
  local-net:
    external: false
volumes:
  test-reports:
    external: false
